spring:
    hadoop:
        fsUri: hdfs://localhost:9000
        resourceManagerHost: localhost
    yarn:
        appName: rg-yarn
        applicationDir: /rg-yarn/
        client:
            localizer:
                patterns:
                  - "*.jar"
            files:
              - "file:rg-yarn.jar"
            launchcontext:
                archiveFile: rg-yarn.jar
        appmaster:
            localizer:
                patterns:
                  - "*.jar"
            containerCount: 3
            launchcontext:
                archiveFile: rg-yarn.jar
